Update requirements.txt
Numpy versions greater than 1 cause the following error on import of ehtim

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject